INSERT INTO users (username, password, email) VALUES ('mauricio', '1234', 'mauro@gmail.com');
INSERT INTO users (username, password, email) VALUES ('JULIO', '45994', 'jujuquerdoce@gmail.com');
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('1984', 'George Orwell', 'Companhia das Letras', 45.90, 'Um clássico distópico sobre um regime totalitário.', 'Ficção', '1949-06-08', 20, 'https://m.media-amazon.com/images/I/81ay5XKxWbL.jpg');
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('A Revolução dos Bichos', 'George Orwell', 'Companhia das Letras', 39.90, 'Uma sátira política sobre uma fazenda tomada por animais.', 'Ficção', '1945-08-17', 18, 'https://m.media-amazon.com/images/I/71UXvTt3ZHL.jpg');
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('Admirável Mundo Novo', 'Aldous Huxley', 'Globo Livros', 49.90, 'Uma sociedade futurista onde a felicidade é obrigatória.', 'Ficção', '1932-01-01', 15, 'https://m.media-amazon.com/images/I/71zvV3C+u0L.jpg');

-- Fantasia
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('O Senhor dos Anéis: A Sociedade do Anel', 'J. R. R. Tolkien', 'HarperCollins', 79.90, 'A jornada épica para destruir o Um Anel.', 'Fantasia', '1954-07-29', 12, 'https://m.media-amazon.com/images/I/81j7v6K6ZlL.jpg');
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('Harry Potter e a Pedra Filosofal', 'J. K. Rowling', 'Rocco', 59.90, 'O início da jornada de Harry Potter em Hogwarts.', 'Fantasia', '1997-06-26', 25, 'https://m.media-amazon.com/images/I/81YOuOGFCJL.jpg');
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('O Nome do Vento', 'Patrick Rothfuss', 'Arqueiro', 69.90, 'A história de Kvothe, um herói lendário e músico prodigioso.', 'Fantasia', '2007-03-27', 10, 'https://m.media-amazon.com/images/I/81R4mDq5I0L.jpg');

-- Romance
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('Orgulho e Preconceito', 'Jane Austen', 'Penguin Companhia', 42.90, 'Um clássico sobre amor e classe social na Inglaterra.', 'Romance', '1813-01-28', 16, 'https://m.media-amazon.com/images/I/81xzF5RddrL.jpg');
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('Como Eu Era Antes de Você', 'Jojo Moyes', 'Intrínseca', 44.90, 'Um romance emocionante sobre amor e escolhas.', 'Romance', '2012-01-05', 22, 'https://m.media-amazon.com/images/I/71b4G+jrA0L.jpg');
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('A Culpa é das Estrelas', 'John Green', 'Intrínseca', 39.90, 'Um jovem casal enfrenta o amor em meio à doença.', 'Romance', '2012-01-10', 19, 'https://m.media-amazon.com/images/I/81uHh3V8u-L.jpg');

-- Terror
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('O Iluminado', 'Stephen King', 'Suma', 59.90, 'Um escritor enlouquece em um hotel isolado.', 'Terror', '1977-01-28', 14, 'https://m.media-amazon.com/images/I/81sCj8tKkqL.jpg');
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('Drácula', 'Bram Stoker', 'DarkSide Books', 64.90, 'O conde Drácula espalha terror pela Inglaterra.', 'Terror', '1897-05-26', 11, 'https://m.media-amazon.com/images/I/81nDW1CjPWL.jpg');
INSERT INTO book (title, author, publisher, price, description, category, release, stock, img_Url) VALUES('Frankenstein', 'Mary Shelley', 'Penguin Classics', 49.90, 'Um cientista cria um monstro e enfrenta as consequências.', 'Terror', '1818-01-01', 17, 'https://m.media-amazon.com/images/I/81P6nQ92cIL.jpg');